# Generated by Django 4.2.4 on 2023-09-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название страны"),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="regions.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Населённый пункт",
                "verbose_name_plural": "Населённые пункты",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                (
                    "building_number",
                    models.CharField(max_length=10, verbose_name="Дом"),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Корпус"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Почтовый индекс",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="regions.city",
                        verbose_name="Населённый пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
    ]
